name: Lighthouse CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: |
        yarn install
        yarn build
    - name: Audit URLs using Lighthouse
      id: lighthouse_audit
      uses: treosh/lighthouse-ci-action@v8
      with:
        urls: |
          https://google.com
          https://vnexpress.net
        configPath: ./.github/workflows/lighthousesrc.json
        uploadArtifacts: true
        temporaryPublicStorage: true
        runs: 1
    - name: Format lighthouse score
      id: format_lighthouse_score
      uses: actions/github-script@v5
      with:
        script: |
          const lighthouseCommentMaker = require('./.github/workflows/lighthouseCommentMaker.js');

          const lighthouseOutputs = {
            manifest: ${{ steps.lighthouse_audit.outputs.manifest }},
            links: ${{ steps.lighthouse_audit.outputs.links }}
          };

          const comment = lighthouseCommentMaker({ lighthouseOutputs });
          core.setOutput("comment", comment);

    - name: Add Lighthouse stats as comment
      id: comment_to_pr
      uses: marocchino/sticky-pull-request-comment@v2.0.0
      with:
        number: ${{ github.event.pull_request.number }}
        header: lighthouse
        message: ${{ steps.format_lighthouse_score.outputs.comment }}
