name: Lighthouse CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: yarn install
      run: |
        yarn install
        yarn build
    - name: lighthouse check
      run: |
        npm install @lhci/cli@0.9.x
        yarn run lhci
